syntax = "proto3";

service AiProcessor {
    rpc ProcessVideo(stream VideoChunk) returns (stream ProcessedVideoChunk);
    rpc AddWhitelist(FaceData) returns (WhitelistResponse);
}

// ProcessVideo
message VideoChunk {
    bytes data = 1;
    int64 timestamp = 2;
}

message ProcessedVideoChunk {
    bytes data = 1;
    int64 timestamp = 2;
    string status_message = 3;
}

// AddWhitelist
message FaceData {
    bytes data = 1;
}

message WhitelistResponse {
    string status_message = 1;
    int64 timestamp = 2;
}