# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import ai_processor_pb2 as protos_dot_ai__processor__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/ai_processor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiProcessorStub:
    """Intentionally no package: existing clients call /AiProcessor/ProcessVideo.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessVideo = channel.stream_stream(
                '/AiProcessor/ProcessVideo',
                request_serializer=protos_dot_ai__processor__pb2.VideoChunk.SerializeToString,
                response_deserializer=protos_dot_ai__processor__pb2.ProcessedVideoChunk.FromString,
                _registered_method=True)
        self.AddWhitelist = channel.unary_unary(
                '/AiProcessor/AddWhitelist',
                request_serializer=protos_dot_ai__processor__pb2.FaceData.SerializeToString,
                response_deserializer=protos_dot_ai__processor__pb2.WhitelistResponse.FromString,
                _registered_method=True)
        self.GetWhitelistStatus = channel.unary_unary(
                '/AiProcessor/GetWhitelistStatus',
                request_serializer=protos_dot_ai__processor__pb2.GetWhitelistStatusRequest.SerializeToString,
                response_deserializer=protos_dot_ai__processor__pb2.GetWhitelistStatusResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/AiProcessor/CreateSession',
                request_serializer=protos_dot_ai__processor__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=protos_dot_ai__processor__pb2.SessionInfo.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/AiProcessor/ListSessions',
                request_serializer=protos_dot_ai__processor__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=protos_dot_ai__processor__pb2.ListSessionsResponse.FromString,
                _registered_method=True)


class AiProcessorServicer:
    """Intentionally no package: existing clients call /AiProcessor/ProcessVideo.
    """

    def ProcessVideo(self, request_iterator, context):
        """One ordered, long-lived video flow per call. A call owns its tracker state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddWhitelist(self, request, context):
        """Adds one face exemplar to the session-scoped in-memory whitelist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWhitelistStatus(self, request, context):
        """Returns non-sensitive whitelist metadata for one session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Atomically creates an opaque session ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Lists in-memory sessions for the authenticated management client.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessVideo,
                    request_deserializer=protos_dot_ai__processor__pb2.VideoChunk.FromString,
                    response_serializer=protos_dot_ai__processor__pb2.ProcessedVideoChunk.SerializeToString,
            ),
            'AddWhitelist': grpc.unary_unary_rpc_method_handler(
                    servicer.AddWhitelist,
                    request_deserializer=protos_dot_ai__processor__pb2.FaceData.FromString,
                    response_serializer=protos_dot_ai__processor__pb2.WhitelistResponse.SerializeToString,
            ),
            'GetWhitelistStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWhitelistStatus,
                    request_deserializer=protos_dot_ai__processor__pb2.GetWhitelistStatusRequest.FromString,
                    response_serializer=protos_dot_ai__processor__pb2.GetWhitelistStatusResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=protos_dot_ai__processor__pb2.CreateSessionRequest.FromString,
                    response_serializer=protos_dot_ai__processor__pb2.SessionInfo.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=protos_dot_ai__processor__pb2.ListSessionsRequest.FromString,
                    response_serializer=protos_dot_ai__processor__pb2.ListSessionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AiProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AiProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiProcessor:
    """Intentionally no package: existing clients call /AiProcessor/ProcessVideo.
    """

    @staticmethod
    def ProcessVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/AiProcessor/ProcessVideo',
            protos_dot_ai__processor__pb2.VideoChunk.SerializeToString,
            protos_dot_ai__processor__pb2.ProcessedVideoChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddWhitelist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AiProcessor/AddWhitelist',
            protos_dot_ai__processor__pb2.FaceData.SerializeToString,
            protos_dot_ai__processor__pb2.WhitelistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWhitelistStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AiProcessor/GetWhitelistStatus',
            protos_dot_ai__processor__pb2.GetWhitelistStatusRequest.SerializeToString,
            protos_dot_ai__processor__pb2.GetWhitelistStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AiProcessor/CreateSession',
            protos_dot_ai__processor__pb2.CreateSessionRequest.SerializeToString,
            protos_dot_ai__processor__pb2.SessionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AiProcessor/ListSessions',
            protos_dot_ai__processor__pb2.ListSessionsRequest.SerializeToString,
            protos_dot_ai__processor__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
